# Only on very first run, DOCKER_STEPCA_INIT variables must be set.
# If you mount a volume to /home/step,
# you persist data and can restart without these INIT values declared.
#
version: "3.7"
services:
  cerberus:
    image: donjulio:5000/smallstep/step-ca:0.27.2
    container_name: cerberus
    hostname: cerberus
#    environment:
#      DOCKER_STEPCA_INIT_NAME: "cerberus.donjulio.local"
#      DOCKER_STEPCA_INIT_DNS_NAMES: cerberus, donjulio, localhost
#      DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT: "TRUE"
#      DOCKER_STEPCA_INIT_PROVISIONER_NAME: "admin"
#      DOCKER_STEPCA_INIT_PASSWORD_FILE: "init.pwd"
    ports:
      - 9000:9000
    volumes:
      - /home/ptschneider/github/my-ca-smallstep/cerberus.donjulio.local:/home/step



